[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
chrono = "0.4.38"
env_logger = "0.11.5"
kuchiki = "0.8.1"
lazy_static = "1.5.0"
log = "0.4.22"
notify = "7.0.0"
tempfile = "3.13.0"
tera = "1.20.0"
